name: deployment

on:
  push:
    branches:
      - "master"
      - "release/production"
      - "feature/deployment"

jobs:
  prepare:
    runs-on: ubuntu-latest
    container: lorisleiva/laravel-docker:8.0
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: composer
        run: |
          composer install --no-dev --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
      - 
        name: npm
        run: |
          npm install
          npm run prod

  build:
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Building Docker
        run: |
          git log --pretty="%H" -n1 HEAD > VERSION
          docker build -t rl-cp .
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          DOCKERTAG=latest-$(echo $GITHUB_REF_NAME | tr -d /)
          [ "$GITHUB_REF_NAME" == "master" ] && DOCKERTAG=latest
          docker tag rl-cp ghcr.io/$GITHUB_REPOSITORY:$DOCKERTAG
          docker push ghcr.io/$GITHUB_REPOSITORY:$DOCKERTAG
          docker rmi rl-cp        
  
  
  deploy-development:
    runs-on: ubuntu-latest
    needs: build
    environment: development
    if: github.ref == 'refs/heads/master'
    steps:
      -
        name: Deploy to development
        run: |
          curl http://${{ secrets.DEPLOYRON_IP }}:6000/deploy/cp_development?APISecret=${{ secrets.DEPLOY_API_SECRET_DEVELOPMENT }}
          
  deploy-production:
    runs-on: ubuntu-latest
    needs: build
    environment: production
    if: github.ref == 'refs/heads/release/production'
    steps:
      -
        name: Deploy to production
        run: |
          curl http://${{ secrets.DEPLOYRON_IP }}:6000/deploy/cp_production?APISecret=${{ secrets.DEPLOY_API_SECRET_PRODUCTION }}
